admin/src/web/controllers/services.py
from datetime import datetime
from flask import Blueprint, render_template, abort
from flask import flash, redirect, url_for, request
from src.forms.servicios_form import ServiciosForm
from src.forms.servicios_form import ActualizarSolicitudesForm
from src.forms.servicios_form import FiltroSolicitudesForm
from src.web.helpers.auth import login_required, has_permissions
from src.web.helpers.institutions import user_in_institution
from src.core import services, instituciones, api
from src.core import configuracion
from src.core import auth


services_bp = Blueprint("services", __name__, url_prefix="/services")


@services_bp.get("/<int:institucion_id>")
@login_required
@user_in_institution
def index(institucion_id):
    """
     Este método se encarga de mostrar los servicios de manera páginada 
     segun el valor que se encuentre en el archivo de configuración.
    """
    if not has_permissions(['services_index']):
        abort(401)
    page = request.args.get('page', type=int, default=1)
    per_page = configuracion.get_per_page()
    paginated_services = services.paginate_services(page, per_page, institucion_id)
    nombre_institucion = instituciones.find_institucion_by_id(institucion_id).nombre
    return render_template("services/index.html",
                           services=paginated_services,
                           institucion_id=institucion_id,
                           nombre=nombre_institucion)


@services_bp.get("/agregar/<int:institucion_id>")
@login_required
@user_in_institution
def agregar(institucion_id):
    if not has_permissions(['services_new']):
        abort(401)
    form = ServiciosForm()
    return render_template("services/agregar_servicio.html",
                           form=form,
                           institucion_id=institucion_id)


@services_bp.post("/agregar_servicio/<int:institucion_id>")
@login_required
@user_in_institution
def agregar_servicio(institucion_id):
    """
    Este método se encarga de de agregar un
    servicio a una institución específica segun su ID
    """
    form = ServiciosForm()
    if form.validate_on_submit():
        services.create_service(
            nombre=form.nombre.data,
            descripcion=form.descripcion.data,
            keywords=form.keywords.data,
            tipo_servicio=form.tipo_servicio.data,
            habilitado=form.habilitado.data,
            institucion=instituciones.find_institucion_by_id(institucion_id)
        )
        flash('Servicio creado con exito', 'success')
        return redirect(url_for('services.index',
                                institucion_id=institucion_id))
    return render_template("services/agregar_servicio.html",
                           form=form,
                           institucion_id=institucion_id)


@services_bp.get("/editar/<int:servicio_id>/<int:institucion_id>")
@login_required
@user_in_institution
def editar(servicio_id, institucion_id):
    if not has_permissions(['services_update']):
        abort(401)
    servicio = services.get_service(servicio_id)
    form = ServiciosForm(obj=servicio)
    return render_template('services/editar_servicio.html',
                           form=form,
                           servicio=servicio,
                           institucion_id=institucion_id)


@services_bp.post("/editar_servicio/<int:servicio_id>/<int:institucion_id>")
@login_required
@user_in_institution
def editar_servicio(servicio_id, institucion_id):
    """
    Este método se encarga de mostrar un formulario para editar un
    servicio con los nuevos datos ingresados por el usuario
    """
    servicio = services.get_service(servicio_id)
    form = ServiciosForm()
    if form.validate_on_submit():
        services.update_service(form, servicio)
        flash('Servicio actualizado correctamente', 'success')
        return redirect(url_for("services.index",
                                institucion_id=institucion_id))
    return render_template('services/editar_servicio.html',
                           form=form,
                           institucion_id=institucion_id)


@services_bp.post("/eliminar/<int:servicio_id>/<int:institucion_id>")
@login_required
@user_in_institution
def eliminar(servicio_id, institucion_id):
    if not has_permissions(['services_destroy']):
        abort(401)
    services.delete_service(servicio_id)
    flash('Servicio eliminado correctamente', 'success')
    return redirect(url_for("services.index", institucion_id=institucion_id))


#------------------------------------------------


@services_bp.route("/index_solicitudes/<int:institucion_id>", methods=['POST', 'GET'])
@login_required
@user_in_institution
def index_solicitudes(institucion_id):
    """
    Este método lista todas las solicitudes y permite filtrarlas
    por un rango de fechas, username del cliente que la realizó
    estado de la solicitud o tipo de servicio de la misma
    """
    if not has_permissions(['solicitudes_index']):
        abort(401)
    form = FiltroSolicitudesForm()  # Asume que tienes un formulario para el filtrado
    page = request.args.get('page', type=int, default=1)
    per_page = configuracion.get_per_page()

    if form.validate_on_submit():
        inicio = None
        fin = None
        estado = None
        tipo = None
        username = None
        if form.fecha_inicio.data:
            inicio = form.fecha_inicio.data

        if form.fecha_fin.data:
            fin = form.fecha_fin.data

        if form.estado.data:
            estado = form.estado.data

        if form.tipo_servicio.data:
            tipo = form.tipo_servicio.data

        if form.cliente_username.data:
            username = form.cliente_username.data
        
        solicitudes = services.paginate_solicitudes_filtradas(page, per_page, inicio, fin, estado, tipo, username, institucion_id)
    else:
        solicitudes = services.paginate_solicitudes(page, per_page, institucion_id)

    return render_template("services/index_solicitudes.html", solicitudes=solicitudes, form=form, institucion_id=institucion_id)


@services_bp.route("/show_solicitud/<int:id>", methods=['POST', 'GET'])
@login_required
def show_solicitud(id):
    if not has_permissions(['solicitudes_show']):
        abort(401)
    solicitud = services.show_solicitud(id)
    cliente = auth.get_user_by_id(solicitud.cliente_id)
    servicio = services.get_service(solicitud.servicio_id)
    return render_template("services/solicitud.html", solicitud=solicitud, cliente=cliente, servicio=servicio)


@services_bp.post("/update_solicitud/<int:id>")
@login_required
def update_solicitud(id):
    """
    Este método permite cambiar el estado de una solicitud.
    Si está 'En proceso' puede ser 'Aceptada' o 'Rechazada',
    y si es 'Aceptada' puede pasar a 'Finalizada' o 'Cancelada'
    Ademas puede realizar una observacion con respecto a 
    dicho cambio y escribir un comentario general en la misma.
    """

    if not has_permissions(['solicitudes_update']):
        abort(401)
    solicitud = services.show_solicitud(id)
    form = ActualizarSolicitudesForm(obj=solicitud)
    form.set_estado_choices(solicitud)

    if form.validate_on_submit():
        if (form.estado.data == solicitud.estado and form.comentario.data != ''):
            services.update_solicitud(solicitud, comentario=form.comentario.data)
        elif (form.comentario.data == ''):
            services.update_solicitud(
                solicitud,
                estado=form.estado.data,
                observacion_cambio_estado=form.observacion_cambio_estado.data,
                fecha_cambio_estado=datetime.utcnow(),
            )
        else:
            services.update_solicitud(
                solicitud,
                estado=form.estado.data,
                observacion_cambio_estado=form.observacion_cambio_estado.data,
                fecha_cambio_estado=datetime.utcnow(),
                comentario=form.comentario.data
            )

        flash('Solicitud actualizada exitosamente', 'success')

        return redirect(url_for('services.show_solicitud', id=solicitud.id))

    return render_template("services/update_solicitud.html", solicitud=solicitud, form=form)


@services_bp.route("/destroy_solicitud/<int:id>", methods=['POST', 'DELETE'])
@login_required
def destroy_solicitud(id):
    if not has_permissions(['solicitudes_destroy']):
        abort(401)
    services.delete_solicitud(id)
    flash('Solicitud eliminada exitosamente', 'success')
    return redirect(url_for('services.index_solicitudes'))

admin/src/web/templates/services/agregar_servicio.html
{% extends "layout.html" %}
{% block title %}Agregar servicio{% endblock %}
{% block content %}
    <h1 class="mb-4">Agregar Servicio</h1>
    <form action="{{ url_for('services.agregar_servicio', institucion_id=institucion_id) }}" method="POST">
        {{ form.hidden_tag() }}
        {{ form.nombre.label(class="form-label") }} 
        {{ form.nombre(class="form-control") }}
        {{ form.descripcion.label(class="form-label") }}
        {{ form.descripcion(class="form-control") }}
        {{ form.keywords.label(class="form-label") }}
        {{ form.keywords(class="form-control") }}
        {{ form.tipo_servicio.label(class="form-label") }}
        {{ form.tipo_servicio(class="form-control") }} <br>
        {{ form.habilitado.label}}
        {{ form.habilitado}}
        <br>
        <br>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
{% endblock %}

admin/src/web/templates/services/editar_servicio.html
{% extends "layout.html" %}
{% block title %}Editar Servicio{% endblock %}

{% block content %}
    <h1 class="mb-4">Editar Servicio</h1>

    <form action="{{ url_for('services.editar_servicio', servicio_id=servicio.id, institucion_id=institucion_id) }}" method="POST">
        {{ form.hidden_tag() }}
        {{ form.nombre.label(class="form-label") }} 
        {{ form.nombre(class="form-control") }}
        {{ form.descripcion.label(class="form-label") }}
        {{ form.descripcion(class="form-control") }}
        {{ form.keywords.label(class="form-label") }}
        {{ form.keywords(class="form-control") }}
        {{ form.tipo_servicio.label(class="form-label") }}
        {{ form.tipo_servicio(class="form-control") }} <br>
        {{ form.habilitado.label}}
        {{ form.habilitado}}
        <br>
        <br>
    <div class="btn-group">
            <button type="submit" class="btn btn-primary" style="margin-right: 10px;" >Editar</button>
        </form>
        {% if has_permissions(['services_destroy']) %}
            <form action="{{ url_for('services.eliminar', servicio_id=servicio.id, institucion_id=institucion_id) }}" method="POST" style="display: inline;">
            <button type="submit" class="btn btn-danger" onclick="return confirm('¿Estás seguro de que deseas borrar este servicio?')">Eliminar</button>
            </form>
        {% endif %}
    </div>
{% endblock %}

admin/src/web/templates/services/index.html
{% extends "layout.html" %}
{% block title %}Listado de servicios{% endblock %}

{% block content %}
<div class="container mt-5">
    <a href="{{ url_for('services.agregar', institucion_id=institucion_id) }}" class="btn btn-primary">Agregar servicio</a>
    <a href="{{ url_for('services.index_solicitudes', institucion_id=institucion_id) }}" method="POST" class="btn btn-primary">Solicitudes de Servicios</a>
    <br>
    <br>
    <h1 class="mb-4">Listado de servicios de {{nombre}}</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Descripcion</th>
                <th>Keywords</th>
                <th>Tipo</th>
                <th>Habilitado</th>
                <th>Editar</th>
            </tr>
        </thead>
        <tbody>
            {% for service in services.items %}
                <tr>
                    <td>{{ service.nombre }}</td>
                    <td>{{ service.descripcion }}</td>
                    <td>{{ service.keywords }}</td>
                    <td>{{ service.tipo_servicio }}</td>
                    <td>
                        {% if service.habilitado %}
                            Habilitado
                        {% else %}
                            Inhabilitado
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{ url_for('services.editar', servicio_id=service.id, institucion_id=institucion_id) }}" class="btn btn-info btn-sm">Editar</a>
                    </td>
                </tr>
            </tr>
            {% endfor %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if services.has_prev %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="First">
                                <span aria-hidden="true">&laquo;&laquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ services.prev_num }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}
                    
                    {% for page_num in services.iter_pages() %}
                        {% if page_num %}
                            <li class="page-item {% if page_num == services.page %}active{% endif %}">
                                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled"><span class="page-link">...</span></li>
                        {% endif %}
                    {% endfor %}
                    
                    {% if services.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ services.next_num }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ services.pages }}" aria-label="Last">
                                <span aria-hidden="true">&raquo;&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </tbody>
    </table>
</div>
{% endblock %}

admin/src/web/templates/services/index_solicitudes.html
{% extends "layout.html" %}
{% block title %}Listado de Solicitudes{% endblock %} 
{% block content %}
<div class="container">
    <h1>Listado de Solicitudes</h1>

    <form method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.fecha_inicio.label(class="control-label") }}
            {{ form.fecha_inicio(class="form-control", placeholder="YYYY-MM-DD HH:MM:SS") }}
        </div>

        <div class="form-group">
            {{ form.fecha_fin.label(class="control-label") }}
            {{ form.fecha_fin(class="form-control", placeholder="YYYY-MM-DD HH:MM:SS") }}
        </div>

        <div class="form-group">
            {{ form.estado.label(class="control-label") }}
            {{ form.estado(class="form-control") }}
        </div>

        <div class="form-group">
            {{ form.tipo_servicio.label(class="control-label") }}
            {{ form.tipo_servicio(class="form-control") }}
        </div>

        <div class="form-group">
            {{ form.cliente_username.label(class="control-label") }}
            {{ form.cliente_username(class="form-control") }}
        </div>

        <button type="submit" class="btn btn-primary">Filtrar</button>
    </form>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Cliente</th>
                <th>Estado</th>
                <th>Tipo de Servicio</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for solicitud in solicitudes %}
            <tr>
                <td>{{ solicitud.id }}</td>
                <td>{{ solicitud.cliente.nombre }}</td>
                <td>{{ solicitud.estado }}</td>
                <td>{{ solicitud.servicio.tipo_servicio }}</td>
                <td>
                    <a href="{{ url_for('services.show_solicitud', id=solicitud.id) }}" class="btn btn-info btn-sm">Ver</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if solicitudes %}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if solicitudes.has_prev %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="First">
                            <span aria-hidden="true">&laquo;&laquo;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ solicitudes.prev_num }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
                {% if solicitudes.iter_pages() != None %}
                    {% for page_num in solicitudes.iter_pages() %}
                        {% if page_num %}
                            <li class="page-item {% if page_num == solicitudes.page %}active{% endif %}">
                                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled"><span class="page-link">...</span></li>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                {% if solicitudes.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ solicitudes.next_num }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ solicitudes.pages }}" aria-label="Last">
                            <span aria-hidden="true">&raquo;&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
</div>
{% endblock %}

admin/src/web/templates/services/solicitud.html
{% extends "layout.html" %}
{% block title %}Solicitud{% endblock %}
{% block content %}

        <h3>SOLICITUD</h3><br>
        <a><b>Nombre del Cliente: </b>{{cliente.nombre}}</a><br>
        <a><b>Email del Cliente: </b>{{cliente.email}}</a><br>
        <a><b>Tipo de Servicio: </b>{{servicio.tipo_servicio}}</a><br>
        <a><b>Fecha de Solicitud: </b>{{solicitud.fecha_creacion.strftime('%Y-%m-%d %H:%M:%S')}}</a><br>
        <a><b>Detalles: </b>{{solicitud.detalles}}</a><br><br>
        <a><b>ESTADO: </b>{{solicitud.estado}}</a><br>
        <a><b>Fecha del último cambio de Estado: </b>{{solicitud.fecha_cambio_estado.strftime('%Y-%m-%d %H:%M:%S')}}</a><br>
        <a><b>Observacion del último cambio: </b>{{solicitud.observacion_cambio_estado}}</a><br><br>

        {% if solicitud.comentario != '' %}
            <a><b>Último comentario del cliente: </b>{{ solicitud.comentario }}</a>
        {% endif %}

    <form method="POST" action="{{ url_for('services.update_solicitud', id=solicitud.id) }}">
        <button type="submit" class="btn btn-primary">Actualizar</button>
    </form><br>
    <form method="POST" action="{{ url_for('services.destroy_solicitud', id=solicitud.id) }}">
        <button type="submit" class="btn btn-primary">Eliminar</button>
    </form>
{% endblock %}

admin/src/web/templates/services/update_solicitud.html
{% extends "layout.html" %}
{% block title %}Actualizar Solicitud{% endblock %}
{% block content %}
<form action="{{ url_for('services.update_solicitud', id=solicitud.id) }}" method="POST">
    {{ form.hidden_tag() }}
    {{ form.estado.label(class="form-control-label") }}
    {{ form.estado(class="form-control") }} <br>
    {{ form.observacion_cambio_estado.label(class="form-label") }}
    {{ form.observacion_cambio_estado(class="form-control")}}
    <br>
    {{ form.submit(class="btn btn-primary") }}
</form>
{% endblock %}