admin/src/web/controllers/maintenance.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort
from src.web.helpers.auth import login_required, has_permissions
from src.web.helpers.maintenance import info_contacto as cache_info_contacto
from forms.maintenance_form import MaintenanceForm
from forms.maintenance_form import ContactoForm
from forms.maintenance_form import paginadoForm
from src.core import configuracion
from src.web.config import cache


maintenance_bp = Blueprint("maintenance", __name__, url_prefix="/maintenance")


@maintenance_bp.get('/')
@login_required
def index():
    if not has_permissions(['config_show']):
        abort(401)
    mensaje = configuracion.get_mensaje()  
    return render_template('configuraciones/maintenance_form.html', form=MaintenanceForm(),mensaje=mensaje)


@maintenance_bp.post('/toggle')
@login_required
def toggle_maintenance():
    """
    Está función se ejecuta cuando interactuamos con la configuración de
    mantenimiento dependiendo de si activamos o desactivamos el modo
    mantenimiento. También actualiza el mensaje que se mostrará.
    """
    if not has_permissions(['config_update']):
        abort(401)
    form = MaintenanceForm()
    if form.validate_on_submit():
        if form.activate_maintenance.data:
            configuracion.update_state(True)
            flash("Se activó modo Mantenimiento: ", "info")
        elif form.deactivate_maintenance.data:
            configuracion.update_state(False)
            flash("Se deactivó modo mantenimiento: ", "info")
        if form.mensaje.data:
            configuracion.update_mensaje(form.mensaje.data)
            flash("Nuevo mensaje guardado con exito ", "info")
        return redirect(url_for('maintenance.index'))


@maintenance_bp.get('/info_contacto')
@login_required
def info_contacto():
    """
    Muestra la informacion de contacto actual
    """
    if not has_permissions(['config_show']):
        abort(401)
    info = configuracion.get_info_contacto()
    return render_template('configuraciones/info_contacto.html', info=info)


@maintenance_bp.get('/contacto')
@login_required
def index_contacto():
    """
    Muestra el formulario para actualizar la informacion de contacto
    """
    if not has_permissions(['config_show']):
        abort(401)
    info = configuracion.get_info_contacto()
    form = ContactoForm(obj=info)
    return render_template('configuraciones/update_info.html', form=form)


@maintenance_bp.post('/update_contacto')
@login_required
def update_contacto():
    """
    Actualiza la información de contacto
    """
    if not has_permissions(['config_update']):
        abort(401)
    form = ContactoForm()
    if form.validate_on_submit():
        configuracion.update_info(form.telefono.data, form.email.data, form.direccion.data)
        cache.delete('info_contacto')
        c = cache_info_contacto()

        flash("Se guardaron los cambios correctamente", "info")
        return redirect(url_for('maintenance.info_contacto'))
    return render_template('configuraciones/update_info.html', form=form)


@maintenance_bp.get('/paginado')
@login_required
def index_paginado():
    if not has_permissions(['config_show']):
        abort(401)
    form = paginadoForm()
    per_page = configuracion.get_per_page()
    return render_template('configuraciones/paginado.html', form=form, per_page = per_page)


@maintenance_bp.post('/update_paginado')
@login_required
def update_paginado():
    if not has_permissions(['config_update']):
        abort(401)
    form = paginadoForm()
    if form.validate_on_submit():
        configuracion.update_per_page(form.per_page.data)
        flash("Se guardaron los cambios correctamente", "info")
        return redirect(url_for('maintenance.index_paginado'))
    return render_template('configuraciones/paginado.html')

admin/src/web/templates/configuraciones/info_contacto.html
{% extends "layout.html" %}
{% block title %}Contacto{% endblock %}
{% block content %}
<h1>Informacion de contacto</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>direccion</th>
            <th>telefono</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ info.direccion }}</td>
            <td>{{ info.telefono }}</td>
            <td>{{ info.email }}</td>
        </tr>
    </tbody>
</table>
<a href="{{ url_for('maintenance.index_contacto') }}" class="btn btn-primary mt-2">Editar</a>
{% endblock %}

admin/src/web/templates/configuraciones/maintenance_form.html
{% extends "layout.html" %}
{% block title %}Mantenimiento{% endblock %}
{% block content %}
<html>
<head>
    <title>Selección de Modo de Mantenimiento</title>
</head>
<body>
    <h1>Activar/Desactivar mantenimiento</h1>      
    <br>
    <h5><span class="text-success ml-0">Mensaje actual:</span> "{{ mensaje }}"</h5>
    <form method="POST" action="{{ url_for('maintenance.toggle_maintenance') }}">
        {{ form.hidden_tag() }}
        {% if not  is_maintenance() %}
             {{ form.activate_maintenance(class="btn btn-secondary mt-3") }}
        {% endif %}
        {% if  is_maintenance() %}
             {{ form.deactivate_maintenance(class="btn btn-secondary mt-3") }}
        {% endif %}
        <br>
        <br>
        {{form.mensaje.label(class="form-label")}}
        {{form.mensaje(class="form-control")}}
        <br>
        {{form.guardar(class="btn btn-primary")}}
    </form>
</body>
</html>
{% endblock %}

admin/src/web/templates/configuraciones/paginado.html
{% extends "layout.html" %}
{% block title %}Contacto{% endblock %}
{% block content %}
<h1>Número de elementos por pagina</h1>
<br>
<form action="{{ url_for('maintenance.update_paginado') }}" method="POST">
        {{ form.hidden_tag() }}
        <h3>paginado actual : {{per_page}} </h3> 
        <strong>{{ form.per_page.label }}</strong>
         {{form.per_page}}
        {{form.guardar(class="btn btn-primary")}}
 </form>       
{% endblock %}

admin/src/web/templates/configuraciones/update_info.html
{% extends "layout.html" %}
{% block title %}Contacto{% endblock %}
{% block content %}
<div class="container mt-5">
    <h1>Editar información de contacto</h1>
    <form action="{{ url_for('maintenance.update_contacto') }}" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            <label for="email">Correo Electrónico</label>
            {{ form.email(class="form-control") }}
            {% for error in form.email.errors %}
                <span style="color: red;">Introduzca un email valido</span>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="telefono">Teléfono</label>
            {{ form.telefono(class="form-control") }}
        </div>
        <div class="form-group">
            <label for="direccion">Dirección</label>
            {{ form.direccion(class="form-control") }}
        </div>
        {{ form.guardar(class="btn btn-primary") }}

    </form>
    <a href="{{ url_for('maintenance.info_contacto') }}" class="btn btn-secondary mt-3">Volver atrás</a>
</div>
{% endblock %}