admin/src/web/controllers/instituciones.py
from flask import Blueprint, render_template, abort, flash, redirect, url_for, request
from src.core import instituciones
from src.web.helpers.auth import login_required, has_permissions
from forms.institucion_form import InstitucionForm
from flask import current_app as app
from src.core import configuracion


instituciones_bp = Blueprint("instituciones", __name__, url_prefix="/instituciones")


@instituciones_bp.route('/', methods=['GET'])
@login_required
def list_instituciones():

    """
    Este método se encarga de traer las instituciones,
    paginadas según las configuraciones aplicadas. 
    """

    if not has_permissions(['institution_index']):
        abort(401)

    page = request.args.get('page', type=int, default=1)
    per_page = configuracion.get_per_page()
    paginated_instits = instituciones.paginate_instituciones(page, per_page)
    return render_template("instituciones/list_instituciones.html", instits=paginated_instits)


@instituciones_bp.route('/<int:id>', methods=['GET'])
@login_required
def show(id):
    if not has_permissions(['institution_show']):
        abort(401)
    instit = instituciones.find_institucion_by_id(id)
    return render_template("instituciones/institucion.html", instit=instit)


@instituciones_bp.route('/habilitar_institucion/<int:id>', methods=['POST'])
@login_required
def habilitar_institucion(id):
    """
    Este método cambia el flag de Habilitado de una institucion.
    Si está habilitada, la deshabilita y viceversa
    """
    if not has_permissions(['institution_update']):
        abort(401)
    instit = instituciones.find_institucion_by_id(id)

    instituciones.habilitar_institucion(instit, not instit.habilitado)

    return render_template("instituciones/institucion.html", instit=instit)

@instituciones_bp.get("/create")
@login_required
def create():
    if not has_permissions(['institution_new']):
        abort(401)
    form = InstitucionForm()
    return render_template("instituciones/create_institucion.html", form=form)


@instituciones_bp.post("/create_institucion")
@login_required
def create_institucion():
    if not has_permissions(['institution_new']):
        abort(401)
    form = InstitucionForm()
    if form.validate_on_submit():
        instituciones.create_institucion(
            nombre=form.nombre.data,
            informacion=form.informacion.data,
            calle=form.calle.data,
            numero=form.numero.data,
            localizacion=form.localizacion.data,
            palabras_claves=form.palabras_claves.data,
            horarios=form.horarios.data,
            web=form.web.data,
            contacto=form.contacto.data
        )
        flash('Institucion agregada exitosamente', 'success')
        return redirect(url_for('instituciones.list_instituciones'))
    return render_template("instituciones/create_institucion.html", form=form)


@instituciones_bp.route('/update/<int:id>', methods=['POST', 'GET'])
@login_required
def update(id):

    """
    Este método actualiza la institución con los
    nuevos valores que se obtienen desde el formulario
    """

    if not has_permissions(['institution_update']):
        abort(401)
    instit = instituciones.find_institucion_by_id(id)

    form = InstitucionForm(obj=instit)

    if form.validate_on_submit():
        instituciones.update_institucion(
            instit,
            nombre=form.nombre.data,
            informacion=form.informacion.data,
            calle=form.calle.data,
            numero=form.numero.data,
            localizacion=form.localizacion.data,
            palabras_claves=form.palabras_claves.data,
            horarios=form.horarios.data,
            web=form.web.data,
            contacto=form.contacto.data
        )

        flash('Institución actualizada exitosamente', 'success')
        return redirect(url_for('instituciones.list_instituciones'))

    return render_template("instituciones/update_institucion.html", instit=instit, form=form)


@instituciones_bp.route('/destroy/<int:id>', methods=['POST', 'DELETE'])
@login_required
def destroy(id):
    if not has_permissions(['institution_destroy']):
        abort(401)
    instituciones.delete_institucion(id)
    flash('Institución eliminada exitosamente', 'success')
    return redirect(url_for('instituciones.list_instituciones'))

admin/src/web/templates/instituciones/create_institucion.html
{% extends "layout.html" %}
{% block title %}Crear institucion{% endblock %}
{% block content %}
<form action="{{ url_for('instituciones.create_institucion') }}" method="POST">
    {{ form.hidden_tag() }}
    {{ form.nombre.label(class="form-label") }} 
    {{ form.nombre(class="form-control")}}
    {{ form.informacion.label(class="form-label") }} 
    {{ form.informacion(class="form-control")}}
    {{ form.calle.label(class="form-label") }}
    {{ form.calle(class="form-control")}}
    {{ form.numero.label(class="form-label") }}
    {{ form.numero(class="form-control")}}
    {{ form.localizacion.label(class="form-label") }}
    {{ form.localizacion(class="form-control")}}
    {{ form.palabras_claves.label(class="form-label") }} 
    {{ form.palabras_claves(class="form-control")}}
    {{ form.horarios.label(class="form-label") }} 
    {{ form.horarios(class="form-control")}}
    {{ form.web.label(class="form-label") }} 
    {{ form.web(class="form-control")}}
    {{ form.contacto.label(class="form-label") }} 
    {{ form.contacto(class="form-control")}}
    <br>
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock %}

admin/src/web/templates/instituciones/institucion.html
{% extends "layout.html" %}
{% block title %}Registro de usuarios{% endblock %}
{% block content %}
<a href="{{ url_for('instituciones.list_instituciones') }}" class="btn btn-outline-primary mt-2">
    <i class="fas fa-arrow-left"></i> Volver atrás
</a>
<br>
<br>
        <a><b>Nombre: </b>{{instit.nombre}}</a><br>
        <a><b>Informacion </b>{{instit.informacion}}</a><br>
        <a><b>Calle: </b>{{instit.calle}}</a><br>
        <a><b>Numero: </b>{{instit.numero}}</a><br>
        <a><b>Localizacion: </b>{{instit.localizacion}}</a><br>
        <a><b>Claves: </b>{{instit.palabras_claves}}</a><br>
        <a><b>Horarios: </b>{{instit.horarios}}</a><br>
        <a><b>Web: </b>{{instit.web}}</a><br>
        <a><b>Contacto: </b>{{instit.contacto}}</a><br>
        {% if instit.habilitado %}
        <a><b>Habilitado: </b>Si</a>
        {% else %}
        <a><b>Habilitado: </b>No</a>
        {% endif %}
    <br>
    <br>
    <form method="POST" action="{{ url_for('instituciones.update', id=instit.id) }}" style="display: inline-block;">
        <button type="submit" class="btn btn-primary">Modificar</button>
    </form>
    <form method="POST" action="{{ url_for('instituciones.habilitar_institucion', id=instit.id) }}" style="display: inline-block;">
        <button type="submit" class="btn btn-primary">
            {% if instit.habilitado %}
                Deshabilitar
            {% else %}
                Habilitar
            {% endif %}
        </button>
    </form>
    <form method="POST" action="{{ url_for('instituciones.destroy', id=instit.id) }}" style="display: inline-block;">
        <button type="submit" class="btn btn-danger" onclick="return confirm('¿Estás seguro de que deseas borrar esta institucion?')">Eliminar</button>
    </form>
        
{% endblock %}

admin/src/web/templates/instituciones/list_instituciones.html
{% extends "layout.html" %}
{% block title %}Registro de Usuarios{% endblock %}
{% block content %}
<a class="btn btn-primary" href="{{ url_for('instituciones.create') }}">Crear Institución</a>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Lista de Instituciones</h1>
            {% if instits %}
                <ul class="list-group">
                    {% for instit in instits.items %}
                        <li class="list-group-item">
                            <b>{{ instit.nombre }}</b> - <a href="{{ url_for('instituciones.show', id=instit.id) }}">Ver Información Completa</a>
                        </li>
                    {% endfor %}
                </ul>
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        {% if instits.has_prev %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1" aria-label="First">
                                    <span aria-hidden="true">&laquo;&laquo;</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ instits.prev_num }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}
                        
                        {% for page_num in instits.iter_pages() %}
                            {% if page_num %}
                                <li class="page-item {% if page_num == instits.page %}active{% endif %}">
                                    <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled"><span class="page-link">...</span></li>
                            {% endif %}
                        {% endfor %}
                        
                        {% if instits.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ instits.next_num }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ instits.pages }}" aria-label="Last">
                                    <span aria-hidden="true">&raquo;&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% else %}
                <p>No hay instituciones.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

admin/src/web/templates/instituciones/update_institucion.html
{% extends "layout.html" %}
{% block title %}Crear institucion{% endblock %}
{% block content %}
<form action="{{ url_for('instituciones.update', id=instit.id) }}" method="POST">
    {{ form.hidden_tag() }}
    {{ form.nombre.label(class="form-label") }} 
    {{ form.nombre(class="form-control")}}
    {{ form.informacion.label(class="form-label") }} 
    {{ form.informacion(class="form-control")}}
    {{ form.calle.label(class="form-label") }}
    {{ form.calle(class="form-control")}}
    {{ form.numero.label(class="form-label") }}
    {{ form.numero(class="form-control")}}
    {{ form.localizacion.label(class="form-label") }}
    {{ form.localizacion(class="form-control")}}
    {{ form.palabras_claves.label(class="form-label") }} 
    {{ form.palabras_claves(class="form-control")}}
    {{ form.horarios.label(class="form-label") }} 
    {{ form.horarios(class="form-control")}}
    {{ form.web.label(class="form-label") }} 
    {{ form.web(class="form-control")}}
    {{ form.contacto.label(class="form-label") }} 
    {{ form.contacto(class="form-control")}}
    <br>
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock %}