admin/src/web/controllers/users.py
from flask import Blueprint, render_template, abort, request
from flask import redirect, url_for, flash
from src.core import auth
from src.core import users
from src.core import instituciones
from src.forms.users_form import CreateUserForm, UpdateUserForm
from src.web.helpers.auth import login_required, has_permissions, user_is_superadmin
from src.core import configuracion

users_bp = Blueprint("users", __name__, url_prefix="/users")


@users_bp.get("/")
@login_required
def index():
    if not has_permissions(['user_index']):
        abort(401)

    page = request.args.get('page', type=int, default=1)
    per_page = configuracion.get_per_page()

    email = request.args.get('email', default="")
    estado = request.args.get('estado', default="todos")

    users = get_users(email, estado, page, per_page)

    return render_template("users/index.html", users=users.items, pagination=users)


def get_users(email, estado, page, per_page):
    return auth.filter_users(email, estado, page, per_page)


@users_bp.get("/profile/<int:user_id>")
@login_required
def user_profile(user_id):
    if not has_permissions(['user_show']):
        abort(401)

    user = auth.get_user_by_id(user_id)
    is_superadmin = user_is_superadmin(user=user)

    instituciones_del_usuario = users.get_user_institutions(user)

    # Obtengo las instituciones y roles del usuario
    instituciones_roles = users.get_user_institutions_and_roles(user)

    # Obtengo todas las instituciones a las que el usuario NO pertenece
    otras_instituciones = [inst for inst in instituciones.list_instituciones()
                           if inst not in instituciones_del_usuario]

    return render_template(
        "users/profile.html",
        user=user,
        user_is_superadmin=is_superadmin,
        instituciones_roles=instituciones_roles,
        otras_instituciones=otras_instituciones
    )


@users_bp.route("/update_user/<int:user_id>", methods=['GET', 'POST'])
@login_required
def update_user(user_id):
    if not has_permissions(['user_update']):
        abort(401)

    user = auth.get_user_by_id(user_id)
    form = UpdateUserForm()

    if form.validate_on_submit():
        if user.email != form.email.data:
            existe = auth.find_user_by_mail(form.email.data)
            if existe:
                flash('Este correo electrónico ya está en uso. Por favor, elige otro.', 'error')
                return redirect(url_for("users.update_user", user_id=user.id))

        auth.update_name_surname_email(user, form.nombre.data, form.apellido.data, form.email.data)
        flash("Usuario actualizado con éxito!", "success")
        return redirect(url_for("users.user_profile", user_id=user.id))

    elif request.method == "GET":
        form.nombre.data = user.nombre
        form.apellido.data = user.apellido
        form.email.data = user.email

    return render_template("users/update_user.html", user_id=user.id, form=form)


@users_bp.post("/update_state/<int:user_id>")
@login_required
def update_state(user_id):
    if not has_permissions(['user_update']):
        abort(401)

    user = auth.get_user_by_id(user_id)
    auth.update_state(user)

    return redirect(url_for("users.user_profile", user_id=user_id))


@users_bp.post("/destroy_user/<int:user_id>")
@login_required
def destroy_user(user_id):
    if not has_permissions(['user_destroy']):
        abort(401)

    user = auth.get_user_by_id(user_id)
    users.cascade_delete_user(user_id)
    auth.delete_user(user)

    flash("Usuario eliminado con éxito", "success")
    return redirect(url_for("users.index"))


@users_bp.route("/create_user", methods=['GET', 'POST'])
@login_required
def create_user():
    if not has_permissions(['user_new']):
        abort(401)

    if request.method == "GET":
        form = CreateUserForm()
        return render_template("users/create_user.html", form=form)

    form = CreateUserForm()
    if form.validate_on_submit():
        existe = auth.find_user_by_mail(form.email.data)
        if existe:
            flash('Este correo electrónico ya está en uso. Por favor, elige otro.', 'error')
            return redirect(url_for("users.create_user"))

        user = auth.create_User(
            email=form.email.data,
            nombre=form.nombre.data,
            apellido=form.apellido.data,
            password=form.contraseña.data,
            token=None,
            activo=True
        )
        flash("Usuario creado con éxito!", "success")
        return redirect(url_for("users.user_profile", user_id=user.id))

    return render_template("users/create_user.html", form=form)


@users_bp.post("/update_role_institution/<int:institution_id>/<int:user_id>")
@login_required
def update_role_institution(institution_id, user_id):
    """
    Esta función actualiza el rol del usuario en una institución.
    Esta implementación es posible ya que sabemos el id de cada rol
    (definido por nosotros en la BD)
    """
    if not has_permissions(['user_update']):
        abort(401)

    new_role = get_role_requested(request.form.get("new_role"))
    if (new_role != -1):
        users.update_role_for_user_in_institution(user_id, institution_id, new_role)
    else:
        users.delete_role_in_institution_to_user_by_id(institution_id, user_id)
    return redirect(url_for("users.user_profile", user_id=user_id))


@users_bp.post("/assign_role_institution/<int:institution_id>/<int:user_id>")
@login_required
def assign_role_institution(institution_id, user_id):
    if not has_permissions(['user_update']):
        abort(401)

    new_role = get_role_requested(request.form.get("new_role"))
    user = auth.get_user_by_id(user_id)
    institution = instituciones.find_institucion_by_id(institution_id)
    role = users.get_role_by_id(new_role)

    users.assign_role_in_institution_to_user(role, institution, user)
    return redirect(url_for("users.user_profile", user_id=user_id))


def get_role_requested(new_role):
    if (new_role == "owner"):
        return 2
    elif (new_role == "admin"):
        return 3
    elif (new_role == "operator"):
        return 4
    elif (new_role == "none"):
        return -1

admin/src/web/templates/users/create_user.html
{% extends "layout.html" %}
{% block title %}Crear usuario{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-4">Creación de usuario</h2>
    <form method="post", action="{{ url_for('users.create_user') }}">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.nombre.label(class="form-control-label") }}
            {{ form.nombre(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.apellido.label(class="form-control-label") }}
            {{ form.apellido(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {{ form.email(class="form-control") }}
            {% if form.email.errors %}
            <ul class="errors">
                {% for error in form.email.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.contraseña.label(class="form-control-label") }}
            {{ form.contraseña(class="form-control") }}
            {% if form.contraseña.errors %}
            <ul class="errors">
                {% for error in form.contraseña.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.confirmar_contraseña.label(class="form-control-label") }}
            {{ form.confirmar_contraseña(class="form-control") }}
            {% if form.confirmar_contraseña.errors %}
            <ul class="errors">
                {% for error in form.confirmar_contraseña.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Crear Usuario</button>
    </form>
</div>
{% endblock %}

admin/src/web/templates/users/index.html
{% extends "layout.html" %}
{% block title %}Listado de usuarios{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Listado de usuarios:</h1>

    <a href="{{ url_for('users.create_user') }}" class="btn btn-primary">Crear usuario</a>

    <form method="GET" action="{{ url_for('users.index') }}" class="form-inline mb-4 mt-3">
        <div class="form-group">
            <input type="text" id="email" name="email" value="{{ request.args.get('email', '') }}" class="form-control" placeholder="Buscar por correo">
        </div>
        <div class="form-group mx-sm-3">
            <select id="estado" name="estado" class="form-control">
                <option value="todos" {% if request.args.get('estado') == 'todos' %} selected {% endif %}>Todos</option>
                <option value="activo" {% if request.args.get('estado') == 'activo' %} selected {% endif %}>Activos</option>
                <option value="bloqueado" {% if request.args.get('estado') == 'bloqueado' %} selected {% endif %}>Bloqueados</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Buscar</button>
    </form>
    
    {% if users %}
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Email</th>
                    <th>Activo</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>{{ user.nombre }}</td>
                    <td>{{ user.apellido }}</td>
                    <td>{{ user.email }}</td>
                    <td>
                        {% if user.activo %}
                            <span class="badge badge-success">SI</span>
                        {% else %}
                            <span class="badge badge-danger">NO</span>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{ url_for('users.user_profile', user_id=user.id) }}" class="btn btn-info btn-sm">Ver perfil</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if pagination.has_prev %}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('users.index', page=1, email=request.args.get('email'), estado=request.args.get('estado')) }}" aria-label="First">
                        <span aria-hidden="true">&laquo;&laquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('users.index', page=pagination.prev_num, email=request.args.get('email'), estado=request.args.get('estado')) }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}
    
            {% for page_num in pagination.iter_pages() %}
                {% if page_num %}
                    <li class="page-item {% if page_num == pagination.page %}active{% endif %}">
                        <a class="page-link" href="{{ url_for('users.index', page=page_num, email=request.args.get('email'), estado=request.args.get('estado')) }}">{{ page_num }}</a>
                    </li>
                {% else %}
                    <li class="page-item disabled"><span class="page-link">...</span></li>
                {% endif %}
            {% endfor %}
    
            {% if pagination.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('users.index', page=pagination.next_num, email=request.args.get('email'), estado=request.args.get('estado')) }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('users.index', page=pagination.pages, email=request.args.get('email'), estado=request.args.get('estado')) }}" aria-label="Last">
                        <span aria-hidden="true">&raquo;&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
    
    {% else %}
        <h2>No se encontraron usuarios</h2>
    {% endif %}
</div>
{% endblock %}

admin/src/web/templates/users/profile.html
{% extends 'layout.html' %}
{% block title %} {{ user.nombre }} {{ user.apellido }} {% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">{{ user.nombre }} {{ user.apellido }}</h1>
    <div class="row">
        <div class="col-md-6">
            <p><strong>Correo electrónico: </strong>{{ user.email }}</p>
            <p><strong>Estado: </strong>
                {% if user.activo %}
                    Activo
                {% else %}
                    Bloqueado
                {% endif %}
            </p>
            {% if not user_is_superadmin %}
                <form method="post" action="{{ url_for('users.update_state', user_id=user.id) }}">
                    <input type="hidden" name="usuario_id" value="{{ user.id }}">
                    <button type="submit" class="btn btn-primary">
                        {% if user.activo %}
                            Bloquear
                        {% else %}
                            Activar
                        {% endif %}
                    </button>
                </form>
                <a href="{{ url_for('users.update_user', user_id=user.id) }}" class="btn btn-primary mt-2">Editar</a>
                <form method="post" action="{{ url_for('users.destroy_user', user_id=user.id) }}">
                    <input type="submit", class="btn btn-danger mt-2", value="Borrar usuario" onclick="return confirm('¿Estas seguro de que queres eliminar a este usuario?');">
                </form>
                <h2 class="mt-2 mb-4">Instituciones y roles: </h2>
                <div class="list-group">
                    
                    <div class="list-group-item list-group-item-action">
                        {% if instituciones_roles %}
                            {% for institucion, rol in instituciones_roles %}
                            <form method="post" action="{{ url_for('users.update_role_institution', institution_id=institucion.id, user_id=user.id) }}">
                                <span>{{ institucion.nombre }} -</span>
                                <select name="new_role" class="form-select" onchange="this.form.submit()">
                                    <option value="owner" {% if rol.nombre == 'owner' %} selected {% endif %}>Dueño</option>
                                    <option value="operator" {% if rol.nombre == 'operator' %} selected {% endif %}>Operador</option>
                                    <option value="admin" {% if rol.nombre == 'admin' %} selected {% endif %}>Administrador</option>
                                </select>
                            </form>
                            {% endfor %}
                        {% endif %}
                        {% if otras_instituciones %}
                            {% for otra_institucion in otras_instituciones %}
                            <form method="post" action="{{ url_for('users.assign_role_institution', institution_id=otra_institucion.id, user_id=user.id) }}">
                                <span>{{ otra_institucion.nombre }} -</span>
                                <select name="new_role" class="form-select" onchange="this.form.submit()">
                                    <option value="asignar" selected>Designar rol</option>
                                    <option value="owner">Dueño</option>
                                    <option value="operator">Operador</option>
                                    <option value="admin">Administrador</option>
                                </select>
                            </form>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            {% endif %}
            

            <a href="{{ url_for('users.index') }}" class="btn btn-outline-primary mt-2">
                <i class="fas fa-arrow-left"></i> Volver atrás
            </a>
        </div>
    </div>
</div>

{% endblock %}

admin/src/web/templates/users/update_user.html
{% extends "layout.html" %}
{% block title %}Crear usuario{% endblock %}

{% block content %}
<div class="container">
    <form method="post" action="{{ url_for('users.update_user', user_id=user_id) }}">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.nombre.label(class="form-control-label") }}
            {{ form.nombre(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.apellido.label(class="form-control-label") }}
            {{ form.apellido(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {{ form.email(class="form-control") }}
            {% if form.email.errors %}
                <ul class="errors">
                    {% for error in form.email.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
    </form>
</div>

{% endblock %}